// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package github

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// AddLabelResult includes the requested fields of the GraphQL type AddLabelsToLabelablePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AddLabelsToLabelable.
type AddLabelResult struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
}

// GetClientMutationId returns AddLabelResult.ClientMutationId, and is useful for accessing the field via an interface.
func (v *AddLabelResult) GetClientMutationId() string { return v.ClientMutationId }

// AddLabelsResponse is returned by AddLabels on success.
type AddLabelsResponse struct {
	// Adds labels to a labelable object.
	AddLabelsToLabelable AddLabelResult `json:"addLabelsToLabelable"`
}

// GetAddLabelsToLabelable returns AddLabelsResponse.AddLabelsToLabelable, and is useful for accessing the field via an interface.
func (v *AddLabelsResponse) GetAddLabelsToLabelable() AddLabelResult { return v.AddLabelsToLabelable }

// ClosePullRequestClosePullRequestClosePullRequestPayload includes the requested fields of the GraphQL type ClosePullRequestPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of ClosePullRequest.
type ClosePullRequestClosePullRequestClosePullRequestPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
}

// GetClientMutationId returns ClosePullRequestClosePullRequestClosePullRequestPayload.ClientMutationId, and is useful for accessing the field via an interface.
func (v *ClosePullRequestClosePullRequestClosePullRequestPayload) GetClientMutationId() string {
	return v.ClientMutationId
}

// ClosePullRequestResponse is returned by ClosePullRequest on success.
type ClosePullRequestResponse struct {
	// Close a pull request.
	ClosePullRequest ClosePullRequestClosePullRequestClosePullRequestPayload `json:"closePullRequest"`
}

// GetClosePullRequest returns ClosePullRequestResponse.ClosePullRequest, and is useful for accessing the field via an interface.
func (v *ClosePullRequestResponse) GetClosePullRequest() ClosePullRequestClosePullRequestClosePullRequestPayload {
	return v.ClosePullRequest
}

// CreateLabelCreateLabelCreateLabelPayload includes the requested fields of the GraphQL type CreateLabelPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreateLabel.
type CreateLabelCreateLabelCreateLabelPayload struct {
	// The new label.
	Label CreateLabelCreateLabelCreateLabelPayloadLabel `json:"label"`
}

// GetLabel returns CreateLabelCreateLabelCreateLabelPayload.Label, and is useful for accessing the field via an interface.
func (v *CreateLabelCreateLabelCreateLabelPayload) GetLabel() CreateLabelCreateLabelCreateLabelPayloadLabel {
	return v.Label
}

// CreateLabelCreateLabelCreateLabelPayloadLabel includes the requested fields of the GraphQL type Label.
// The GraphQL type's documentation follows.
//
// A label for categorizing Issues, Pull Requests, Milestones, or Discussions with a given Repository.
type CreateLabelCreateLabelCreateLabelPayloadLabel struct {
	// The Node ID of the Label object
	Id string `json:"id"`
}

// GetId returns CreateLabelCreateLabelCreateLabelPayloadLabel.Id, and is useful for accessing the field via an interface.
func (v *CreateLabelCreateLabelCreateLabelPayloadLabel) GetId() string { return v.Id }

// CreateLabelResponse is returned by CreateLabel on success.
type CreateLabelResponse struct {
	// Creates a new label.
	CreateLabel CreateLabelCreateLabelCreateLabelPayload `json:"createLabel"`
}

// GetCreateLabel returns CreateLabelResponse.CreateLabel, and is useful for accessing the field via an interface.
func (v *CreateLabelResponse) GetCreateLabel() CreateLabelCreateLabelCreateLabelPayload {
	return v.CreateLabel
}

// CreatePullRequestFields includes the GraphQL fields of CreatePullRequestPayload requested by the fragment CreatePullRequestFields.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreatePullRequest.
type CreatePullRequestFields struct {
	// The new pull request.
	PullRequest PullRequest `json:"pullRequest"`
}

// GetPullRequest returns CreatePullRequestFields.PullRequest, and is useful for accessing the field via an interface.
func (v *CreatePullRequestFields) GetPullRequest() PullRequest { return v.PullRequest }

// CreatePullRequestResponse is returned by CreatePullRequest on success.
type CreatePullRequestResponse struct {
	// Create a new pull request
	CreatePullRequest CreatePullRequestFields `json:"createPullRequest"`
}

// GetCreatePullRequest returns CreatePullRequestResponse.CreatePullRequest, and is useful for accessing the field via an interface.
func (v *CreatePullRequestResponse) GetCreatePullRequest() CreatePullRequestFields {
	return v.CreatePullRequest
}

// CreateRefResponse is returned by CreateRef on success.
type CreateRefResponse struct {
	// Create a new Git Ref.
	CreateRef CreateRefResult `json:"createRef"`
}

// GetCreateRef returns CreateRefResponse.CreateRef, and is useful for accessing the field via an interface.
func (v *CreateRefResponse) GetCreateRef() CreateRefResult { return v.CreateRef }

// CreateRefResult includes the requested fields of the GraphQL type CreateRefPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreateRef.
type CreateRefResult struct {
	// The newly created ref.
	Ref Ref `json:"ref"`
}

// GetRef returns CreateRefResult.Ref, and is useful for accessing the field via an interface.
func (v *CreateRefResult) GetRef() Ref { return v.Ref }

// DeleteLabelDeleteLabelDeleteLabelPayload includes the requested fields of the GraphQL type DeleteLabelPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of DeleteLabel.
type DeleteLabelDeleteLabelDeleteLabelPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
}

// GetClientMutationId returns DeleteLabelDeleteLabelDeleteLabelPayload.ClientMutationId, and is useful for accessing the field via an interface.
func (v *DeleteLabelDeleteLabelDeleteLabelPayload) GetClientMutationId() string {
	return v.ClientMutationId
}

// DeleteLabelResponse is returned by DeleteLabel on success.
type DeleteLabelResponse struct {
	// Deletes a label.
	DeleteLabel DeleteLabelDeleteLabelDeleteLabelPayload `json:"deleteLabel"`
}

// GetDeleteLabel returns DeleteLabelResponse.DeleteLabel, and is useful for accessing the field via an interface.
func (v *DeleteLabelResponse) GetDeleteLabel() DeleteLabelDeleteLabelDeleteLabelPayload {
	return v.DeleteLabel
}

// GetPullRequestRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type GetPullRequestRepository struct {
	// Returns a single pull request from the current repository by number.
	PullRequest GetPullRequestRepositoryPullRequest `json:"pullRequest"`
}

// GetPullRequest returns GetPullRequestRepository.PullRequest, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepository) GetPullRequest() GetPullRequestRepositoryPullRequest {
	return v.PullRequest
}

// GetPullRequestRepositoryPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type GetPullRequestRepositoryPullRequest struct {
	PullRequest `json:"-"`
	// A list of labels associated with the object.
	Labels GetPullRequestRepositoryPullRequestLabelsLabelConnection `json:"labels"`
}

// GetLabels returns GetPullRequestRepositoryPullRequest.Labels, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetLabels() GetPullRequestRepositoryPullRequestLabelsLabelConnection {
	return v.Labels
}

// GetTitle returns GetPullRequestRepositoryPullRequest.Title, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetTitle() string { return v.PullRequest.Title }

// GetId returns GetPullRequestRepositoryPullRequest.Id, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetId() string { return v.PullRequest.Id }

// GetResourcePath returns GetPullRequestRepositoryPullRequest.ResourcePath, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetResourcePath() string {
	return v.PullRequest.ResourcePath
}

// GetPermalink returns GetPullRequestRepositoryPullRequest.Permalink, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetPermalink() string { return v.PullRequest.Permalink }

// GetUrl returns GetPullRequestRepositoryPullRequest.Url, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetUrl() string { return v.PullRequest.Url }

// GetCreatedAt returns GetPullRequestRepositoryPullRequest.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetCreatedAt() time.Time {
	return v.PullRequest.CreatedAt
}

// GetClosed returns GetPullRequestRepositoryPullRequest.Closed, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetClosed() bool { return v.PullRequest.Closed }

// GetMerged returns GetPullRequestRepositoryPullRequest.Merged, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetMerged() bool { return v.PullRequest.Merged }

// GetNumber returns GetPullRequestRepositoryPullRequest.Number, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetNumber() int { return v.PullRequest.Number }

// GetAuthor returns GetPullRequestRepositoryPullRequest.Author, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequest) GetAuthor() PullRequestAuthor {
	return v.PullRequest.Author
}

func (v *GetPullRequestRepositoryPullRequest) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetPullRequestRepositoryPullRequest
		graphql.NoUnmarshalJSON
	}
	firstPass.GetPullRequestRepositoryPullRequest = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.PullRequest)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetPullRequestRepositoryPullRequest struct {
	Labels GetPullRequestRepositoryPullRequestLabelsLabelConnection `json:"labels"`

	Title string `json:"title"`

	Id string `json:"id"`

	ResourcePath string `json:"resourcePath"`

	Permalink string `json:"permalink"`

	Url string `json:"url"`

	CreatedAt time.Time `json:"createdAt"`

	Closed bool `json:"closed"`

	Merged bool `json:"merged"`

	Number int `json:"number"`

	Author json.RawMessage `json:"author"`
}

func (v *GetPullRequestRepositoryPullRequest) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetPullRequestRepositoryPullRequest) __premarshalJSON() (*__premarshalGetPullRequestRepositoryPullRequest, error) {
	var retval __premarshalGetPullRequestRepositoryPullRequest

	retval.Labels = v.Labels
	retval.Title = v.PullRequest.Title
	retval.Id = v.PullRequest.Id
	retval.ResourcePath = v.PullRequest.ResourcePath
	retval.Permalink = v.PullRequest.Permalink
	retval.Url = v.PullRequest.Url
	retval.CreatedAt = v.PullRequest.CreatedAt
	retval.Closed = v.PullRequest.Closed
	retval.Merged = v.PullRequest.Merged
	retval.Number = v.PullRequest.Number
	{

		dst := &retval.Author
		src := v.PullRequest.Author
		var err error
		*dst, err = __marshalPullRequestAuthor(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GetPullRequestRepositoryPullRequest.PullRequest.Author: %w", err)
		}
	}
	return &retval, nil
}

// GetPullRequestRepositoryPullRequestLabelsLabelConnection includes the requested fields of the GraphQL type LabelConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Label.
type GetPullRequestRepositoryPullRequestLabelsLabelConnection struct {
	// A list of nodes.
	Nodes []Label `json:"nodes"`
}

// GetNodes returns GetPullRequestRepositoryPullRequestLabelsLabelConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetPullRequestRepositoryPullRequestLabelsLabelConnection) GetNodes() []Label { return v.Nodes }

// GetPullRequestResponse is returned by GetPullRequest on success.
type GetPullRequestResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository GetPullRequestRepository `json:"repository"`
}

// GetRepository returns GetPullRequestResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetPullRequestResponse) GetRepository() GetPullRequestRepository { return v.Repository }

// GetRepoRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type GetRepoRepository struct {
	// The Node ID of the Repository object
	Id string `json:"id"`
	// A list of labels associated with the repository.
	Labels RepoLabels `json:"labels"`
}

// GetId returns GetRepoRepository.Id, and is useful for accessing the field via an interface.
func (v *GetRepoRepository) GetId() string { return v.Id }

// GetLabels returns GetRepoRepository.Labels, and is useful for accessing the field via an interface.
func (v *GetRepoRepository) GetLabels() RepoLabels { return v.Labels }

// GetRepoResponse is returned by GetRepo on success.
type GetRepoResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository GetRepoRepository `json:"repository"`
}

// GetRepository returns GetRepoResponse.Repository, and is useful for accessing the field via an interface.
func (v *GetRepoResponse) GetRepository() GetRepoRepository { return v.Repository }

// Label includes the GraphQL fields of Label requested by the fragment Label.
// The GraphQL type's documentation follows.
//
// A label for categorizing Issues, Pull Requests, Milestones, or Discussions with a given Repository.
type Label struct {
	// Identifies the label name.
	Name string `json:"name"`
	// The Node ID of the Label object
	Id string `json:"id"`
	// Identifies the label color.
	Color string `json:"color"`
	// A brief description of this label.
	Description string `json:"description"`
}

// GetName returns Label.Name, and is useful for accessing the field via an interface.
func (v *Label) GetName() string { return v.Name }

// GetId returns Label.Id, and is useful for accessing the field via an interface.
func (v *Label) GetId() string { return v.Id }

// GetColor returns Label.Color, and is useful for accessing the field via an interface.
func (v *Label) GetColor() string { return v.Color }

// GetDescription returns Label.Description, and is useful for accessing the field via an interface.
func (v *Label) GetDescription() string { return v.Description }

// PageInfo includes the GraphQL fields of PageInfo requested by the fragment PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type PageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns PageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *PageInfo) GetEndCursor() string { return v.EndCursor }

// GetHasNextPage returns PageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *PageInfo) GetHasNextPage() bool { return v.HasNextPage }

// PrLabels includes the requested fields of the GraphQL type LabelConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Label.
type PrLabels struct {
	// A list of nodes.
	Nodes []Label `json:"nodes"`
	// Information to aid in pagination.
	PageInfo PageInfo `json:"pageInfo"`
}

// GetNodes returns PrLabels.Nodes, and is useful for accessing the field via an interface.
func (v *PrLabels) GetNodes() []Label { return v.Nodes }

// GetPageInfo returns PrLabels.PageInfo, and is useful for accessing the field via an interface.
func (v *PrLabels) GetPageInfo() PageInfo { return v.PageInfo }

// PullRequest includes the GraphQL fields of PullRequest requested by the fragment PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type PullRequest struct {
	// Identifies the pull request title.
	Title string `json:"title"`
	// The Node ID of the PullRequest object
	Id string `json:"id"`
	// The HTTP path for this pull request.
	ResourcePath string `json:"resourcePath"`
	// The permalink to the pull request.
	Permalink string `json:"permalink"`
	// The HTTP URL for this pull request.
	Url string `json:"url"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// `true` if the pull request is closed
	Closed bool `json:"closed"`
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// Identifies the pull request number.
	Number int `json:"number"`
	// The actor who authored the comment.
	Author PullRequestAuthor `json:"-"`
	// A list of labels associated with the object.
	Labels PrLabels `json:"labels"`
}

// GetTitle returns PullRequest.Title, and is useful for accessing the field via an interface.
func (v *PullRequest) GetTitle() string { return v.Title }

// GetId returns PullRequest.Id, and is useful for accessing the field via an interface.
func (v *PullRequest) GetId() string { return v.Id }

// GetResourcePath returns PullRequest.ResourcePath, and is useful for accessing the field via an interface.
func (v *PullRequest) GetResourcePath() string { return v.ResourcePath }

// GetPermalink returns PullRequest.Permalink, and is useful for accessing the field via an interface.
func (v *PullRequest) GetPermalink() string { return v.Permalink }

// GetUrl returns PullRequest.Url, and is useful for accessing the field via an interface.
func (v *PullRequest) GetUrl() string { return v.Url }

// GetCreatedAt returns PullRequest.CreatedAt, and is useful for accessing the field via an interface.
func (v *PullRequest) GetCreatedAt() time.Time { return v.CreatedAt }

// GetClosed returns PullRequest.Closed, and is useful for accessing the field via an interface.
func (v *PullRequest) GetClosed() bool { return v.Closed }

// GetMerged returns PullRequest.Merged, and is useful for accessing the field via an interface.
func (v *PullRequest) GetMerged() bool { return v.Merged }

// GetNumber returns PullRequest.Number, and is useful for accessing the field via an interface.
func (v *PullRequest) GetNumber() int { return v.Number }

// GetAuthor returns PullRequest.Author, and is useful for accessing the field via an interface.
func (v *PullRequest) GetAuthor() PullRequestAuthor { return v.Author }

// GetLabels returns PullRequest.Labels, and is useful for accessing the field via an interface.
func (v *PullRequest) GetLabels() PrLabels { return v.Labels }

func (v *PullRequest) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*PullRequest
		Author json.RawMessage `json:"author"`
		graphql.NoUnmarshalJSON
	}
	firstPass.PullRequest = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Author
		src := firstPass.Author
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalPullRequestAuthor(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal PullRequest.Author: %w", err)
			}
		}
	}
	return nil
}

type __premarshalPullRequest struct {
	Title string `json:"title"`

	Id string `json:"id"`

	ResourcePath string `json:"resourcePath"`

	Permalink string `json:"permalink"`

	Url string `json:"url"`

	CreatedAt time.Time `json:"createdAt"`

	Closed bool `json:"closed"`

	Merged bool `json:"merged"`

	Number int `json:"number"`

	Author json.RawMessage `json:"author"`

	Labels PrLabels `json:"labels"`
}

func (v *PullRequest) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *PullRequest) __premarshalJSON() (*__premarshalPullRequest, error) {
	var retval __premarshalPullRequest

	retval.Title = v.Title
	retval.Id = v.Id
	retval.ResourcePath = v.ResourcePath
	retval.Permalink = v.Permalink
	retval.Url = v.Url
	retval.CreatedAt = v.CreatedAt
	retval.Closed = v.Closed
	retval.Merged = v.Merged
	retval.Number = v.Number
	{

		dst := &retval.Author
		src := v.Author
		var err error
		*dst, err = __marshalPullRequestAuthor(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal PullRequest.Author: %w", err)
		}
	}
	retval.Labels = v.Labels
	return &retval, nil
}

// PullRequestAuthor includes the requested fields of the GraphQL interface Actor.
//
// PullRequestAuthor is implemented by the following types:
// PullRequestAuthorBot
// PullRequestAuthorEnterpriseUserAccount
// PullRequestAuthorMannequin
// PullRequestAuthorOrganization
// PullRequestAuthorUser
// The GraphQL type's documentation follows.
//
// Represents an object which can take actions on GitHub. Typically a User or Bot.
type PullRequestAuthor interface {
	implementsGraphQLInterfacePullRequestAuthor()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetLogin returns the interface-field "login" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// The username of the actor.
	GetLogin() string
}

func (v *PullRequestAuthorBot) implementsGraphQLInterfacePullRequestAuthor()                   {}
func (v *PullRequestAuthorEnterpriseUserAccount) implementsGraphQLInterfacePullRequestAuthor() {}
func (v *PullRequestAuthorMannequin) implementsGraphQLInterfacePullRequestAuthor()             {}
func (v *PullRequestAuthorOrganization) implementsGraphQLInterfacePullRequestAuthor()          {}
func (v *PullRequestAuthorUser) implementsGraphQLInterfacePullRequestAuthor()                  {}

func __unmarshalPullRequestAuthor(b []byte, v *PullRequestAuthor) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Bot":
		*v = new(PullRequestAuthorBot)
		return json.Unmarshal(b, *v)
	case "EnterpriseUserAccount":
		*v = new(PullRequestAuthorEnterpriseUserAccount)
		return json.Unmarshal(b, *v)
	case "Mannequin":
		*v = new(PullRequestAuthorMannequin)
		return json.Unmarshal(b, *v)
	case "Organization":
		*v = new(PullRequestAuthorOrganization)
		return json.Unmarshal(b, *v)
	case "User":
		*v = new(PullRequestAuthorUser)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Actor.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for PullRequestAuthor: "%v"`, tn.TypeName)
	}
}

func __marshalPullRequestAuthor(v *PullRequestAuthor) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *PullRequestAuthorBot:
		typename = "Bot"

		result := struct {
			TypeName string `json:"__typename"`
			*PullRequestAuthorBot
		}{typename, v}
		return json.Marshal(result)
	case *PullRequestAuthorEnterpriseUserAccount:
		typename = "EnterpriseUserAccount"

		result := struct {
			TypeName string `json:"__typename"`
			*PullRequestAuthorEnterpriseUserAccount
		}{typename, v}
		return json.Marshal(result)
	case *PullRequestAuthorMannequin:
		typename = "Mannequin"

		result := struct {
			TypeName string `json:"__typename"`
			*PullRequestAuthorMannequin
		}{typename, v}
		return json.Marshal(result)
	case *PullRequestAuthorOrganization:
		typename = "Organization"

		result := struct {
			TypeName string `json:"__typename"`
			*PullRequestAuthorOrganization
		}{typename, v}
		return json.Marshal(result)
	case *PullRequestAuthorUser:
		typename = "User"

		result := struct {
			TypeName string `json:"__typename"`
			*PullRequestAuthorUser
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for PullRequestAuthor: "%T"`, v)
	}
}

// PullRequestAuthorBot includes the requested fields of the GraphQL type Bot.
// The GraphQL type's documentation follows.
//
// A special type of user which takes actions on behalf of GitHub Apps.
type PullRequestAuthorBot struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns PullRequestAuthorBot.Typename, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorBot) GetTypename() string { return v.Typename }

// GetLogin returns PullRequestAuthorBot.Login, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorBot) GetLogin() string { return v.Login }

// PullRequestAuthorEnterpriseUserAccount includes the requested fields of the GraphQL type EnterpriseUserAccount.
// The GraphQL type's documentation follows.
//
// An account for a user who is an admin of an enterprise or a member of an enterprise through one or more organizations.
type PullRequestAuthorEnterpriseUserAccount struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns PullRequestAuthorEnterpriseUserAccount.Typename, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorEnterpriseUserAccount) GetTypename() string { return v.Typename }

// GetLogin returns PullRequestAuthorEnterpriseUserAccount.Login, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorEnterpriseUserAccount) GetLogin() string { return v.Login }

// PullRequestAuthorMannequin includes the requested fields of the GraphQL type Mannequin.
// The GraphQL type's documentation follows.
//
// A placeholder user for attribution of imported data on GitHub.
type PullRequestAuthorMannequin struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns PullRequestAuthorMannequin.Typename, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorMannequin) GetTypename() string { return v.Typename }

// GetLogin returns PullRequestAuthorMannequin.Login, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorMannequin) GetLogin() string { return v.Login }

// PullRequestAuthorOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An account on GitHub, with one or more owners, that has repositories, members and teams.
type PullRequestAuthorOrganization struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns PullRequestAuthorOrganization.Typename, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorOrganization) GetTypename() string { return v.Typename }

// GetLogin returns PullRequestAuthorOrganization.Login, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorOrganization) GetLogin() string { return v.Login }

// PullRequestAuthorUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type PullRequestAuthorUser struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns PullRequestAuthorUser.Typename, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorUser) GetTypename() string { return v.Typename }

// GetLogin returns PullRequestAuthorUser.Login, and is useful for accessing the field via an interface.
func (v *PullRequestAuthorUser) GetLogin() string { return v.Login }

// PullRequestsResult includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type PullRequestsResult struct {
	// A list of nodes.
	Nodes []PullRequest `json:"nodes"`
	// Information to aid in pagination.
	PageInfo PageInfo `json:"pageInfo"`
}

// GetNodes returns PullRequestsResult.Nodes, and is useful for accessing the field via an interface.
func (v *PullRequestsResult) GetNodes() []PullRequest { return v.Nodes }

// GetPageInfo returns PullRequestsResult.PageInfo, and is useful for accessing the field via an interface.
func (v *PullRequestsResult) GetPageInfo() PageInfo { return v.PageInfo }

// Ref includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type Ref struct {
	// The Node ID of the Ref object
	Id string `json:"id"`
	// The ref name.
	Name string `json:"name"`
	// The object the ref points to. Returns null when object does not exist.
	Target RefTargetGitObject `json:"-"`
}

// GetId returns Ref.Id, and is useful for accessing the field via an interface.
func (v *Ref) GetId() string { return v.Id }

// GetName returns Ref.Name, and is useful for accessing the field via an interface.
func (v *Ref) GetName() string { return v.Name }

// GetTarget returns Ref.Target, and is useful for accessing the field via an interface.
func (v *Ref) GetTarget() RefTargetGitObject { return v.Target }

func (v *Ref) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*Ref
		Target json.RawMessage `json:"target"`
		graphql.NoUnmarshalJSON
	}
	firstPass.Ref = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Target
		src := firstPass.Target
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalRefTargetGitObject(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal Ref.Target: %w", err)
			}
		}
	}
	return nil
}

type __premarshalRef struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Target json.RawMessage `json:"target"`
}

func (v *Ref) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *Ref) __premarshalJSON() (*__premarshalRef, error) {
	var retval __premarshalRef

	retval.Id = v.Id
	retval.Name = v.Name
	{

		dst := &retval.Target
		src := v.Target
		var err error
		*dst, err = __marshalRefTargetGitObject(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal Ref.Target: %w", err)
		}
	}
	return &retval, nil
}

// RefTargetBlob includes the requested fields of the GraphQL type Blob.
// The GraphQL type's documentation follows.
//
// Represents a Git blob.
type RefTargetBlob struct {
	Typename string `json:"__typename"`
	// The Node ID of the GitObject object
	Id string `json:"id"`
	// The HTTP path for this Git object
	CommitResourcePath string `json:"commitResourcePath"`
	// The Git object ID
	Oid string `json:"oid"`
}

// GetTypename returns RefTargetBlob.Typename, and is useful for accessing the field via an interface.
func (v *RefTargetBlob) GetTypename() string { return v.Typename }

// GetId returns RefTargetBlob.Id, and is useful for accessing the field via an interface.
func (v *RefTargetBlob) GetId() string { return v.Id }

// GetCommitResourcePath returns RefTargetBlob.CommitResourcePath, and is useful for accessing the field via an interface.
func (v *RefTargetBlob) GetCommitResourcePath() string { return v.CommitResourcePath }

// GetOid returns RefTargetBlob.Oid, and is useful for accessing the field via an interface.
func (v *RefTargetBlob) GetOid() string { return v.Oid }

// RefTargetCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type RefTargetCommit struct {
	Typename string `json:"__typename"`
	// The Node ID of the GitObject object
	Id string `json:"id"`
	// The HTTP path for this Git object
	CommitResourcePath string `json:"commitResourcePath"`
	// The Git object ID
	Oid string `json:"oid"`
}

// GetTypename returns RefTargetCommit.Typename, and is useful for accessing the field via an interface.
func (v *RefTargetCommit) GetTypename() string { return v.Typename }

// GetId returns RefTargetCommit.Id, and is useful for accessing the field via an interface.
func (v *RefTargetCommit) GetId() string { return v.Id }

// GetCommitResourcePath returns RefTargetCommit.CommitResourcePath, and is useful for accessing the field via an interface.
func (v *RefTargetCommit) GetCommitResourcePath() string { return v.CommitResourcePath }

// GetOid returns RefTargetCommit.Oid, and is useful for accessing the field via an interface.
func (v *RefTargetCommit) GetOid() string { return v.Oid }

// RefTargetGitObject includes the requested fields of the GraphQL interface GitObject.
//
// RefTargetGitObject is implemented by the following types:
// RefTargetBlob
// RefTargetCommit
// RefTargetTag
// RefTargetTree
// The GraphQL type's documentation follows.
//
// Represents a Git object.
type RefTargetGitObject interface {
	implementsGraphQLInterfaceRefTargetGitObject()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// The Node ID of the GitObject object
	GetId() string
	// GetCommitResourcePath returns the interface-field "commitResourcePath" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// The HTTP path for this Git object
	GetCommitResourcePath() string
	// GetOid returns the interface-field "oid" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// The Git object ID
	GetOid() string
}

func (v *RefTargetBlob) implementsGraphQLInterfaceRefTargetGitObject()   {}
func (v *RefTargetCommit) implementsGraphQLInterfaceRefTargetGitObject() {}
func (v *RefTargetTag) implementsGraphQLInterfaceRefTargetGitObject()    {}
func (v *RefTargetTree) implementsGraphQLInterfaceRefTargetGitObject()   {}

func __unmarshalRefTargetGitObject(b []byte, v *RefTargetGitObject) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Blob":
		*v = new(RefTargetBlob)
		return json.Unmarshal(b, *v)
	case "Commit":
		*v = new(RefTargetCommit)
		return json.Unmarshal(b, *v)
	case "Tag":
		*v = new(RefTargetTag)
		return json.Unmarshal(b, *v)
	case "Tree":
		*v = new(RefTargetTree)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing GitObject.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for RefTargetGitObject: "%v"`, tn.TypeName)
	}
}

func __marshalRefTargetGitObject(v *RefTargetGitObject) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *RefTargetBlob:
		typename = "Blob"

		result := struct {
			TypeName string `json:"__typename"`
			*RefTargetBlob
		}{typename, v}
		return json.Marshal(result)
	case *RefTargetCommit:
		typename = "Commit"

		result := struct {
			TypeName string `json:"__typename"`
			*RefTargetCommit
		}{typename, v}
		return json.Marshal(result)
	case *RefTargetTag:
		typename = "Tag"

		result := struct {
			TypeName string `json:"__typename"`
			*RefTargetTag
		}{typename, v}
		return json.Marshal(result)
	case *RefTargetTree:
		typename = "Tree"

		result := struct {
			TypeName string `json:"__typename"`
			*RefTargetTree
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for RefTargetGitObject: "%T"`, v)
	}
}

// RefTargetTag includes the requested fields of the GraphQL type Tag.
// The GraphQL type's documentation follows.
//
// Represents a Git tag.
type RefTargetTag struct {
	Typename string `json:"__typename"`
	// The Node ID of the GitObject object
	Id string `json:"id"`
	// The HTTP path for this Git object
	CommitResourcePath string `json:"commitResourcePath"`
	// The Git object ID
	Oid string `json:"oid"`
}

// GetTypename returns RefTargetTag.Typename, and is useful for accessing the field via an interface.
func (v *RefTargetTag) GetTypename() string { return v.Typename }

// GetId returns RefTargetTag.Id, and is useful for accessing the field via an interface.
func (v *RefTargetTag) GetId() string { return v.Id }

// GetCommitResourcePath returns RefTargetTag.CommitResourcePath, and is useful for accessing the field via an interface.
func (v *RefTargetTag) GetCommitResourcePath() string { return v.CommitResourcePath }

// GetOid returns RefTargetTag.Oid, and is useful for accessing the field via an interface.
func (v *RefTargetTag) GetOid() string { return v.Oid }

// RefTargetTree includes the requested fields of the GraphQL type Tree.
// The GraphQL type's documentation follows.
//
// Represents a Git tree.
type RefTargetTree struct {
	Typename string `json:"__typename"`
	// The Node ID of the GitObject object
	Id string `json:"id"`
	// The HTTP path for this Git object
	CommitResourcePath string `json:"commitResourcePath"`
	// The Git object ID
	Oid string `json:"oid"`
}

// GetTypename returns RefTargetTree.Typename, and is useful for accessing the field via an interface.
func (v *RefTargetTree) GetTypename() string { return v.Typename }

// GetId returns RefTargetTree.Id, and is useful for accessing the field via an interface.
func (v *RefTargetTree) GetId() string { return v.Id }

// GetCommitResourcePath returns RefTargetTree.CommitResourcePath, and is useful for accessing the field via an interface.
func (v *RefTargetTree) GetCommitResourcePath() string { return v.CommitResourcePath }

// GetOid returns RefTargetTree.Oid, and is useful for accessing the field via an interface.
func (v *RefTargetTree) GetOid() string { return v.Oid }

// Release includes the GraphQL fields of Release requested by the fragment Release.
// The GraphQL type's documentation follows.
//
// A release contains the content for a release.
type Release struct {
	// The Node ID of the Release object
	Id string `json:"id"`
	// The title of the release.
	Name string `json:"name"`
	// The name of the release's Git tag
	TagName string `json:"tagName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// Identifies the date and time when the release was created.
	PublishedAt time.Time `json:"publishedAt"`
	// The description of the release.
	Description string `json:"description"`
	// The HTTP URL for this issue
	Url string `json:"url"`
}

// GetId returns Release.Id, and is useful for accessing the field via an interface.
func (v *Release) GetId() string { return v.Id }

// GetName returns Release.Name, and is useful for accessing the field via an interface.
func (v *Release) GetName() string { return v.Name }

// GetTagName returns Release.TagName, and is useful for accessing the field via an interface.
func (v *Release) GetTagName() string { return v.TagName }

// GetCreatedAt returns Release.CreatedAt, and is useful for accessing the field via an interface.
func (v *Release) GetCreatedAt() time.Time { return v.CreatedAt }

// GetPublishedAt returns Release.PublishedAt, and is useful for accessing the field via an interface.
func (v *Release) GetPublishedAt() time.Time { return v.PublishedAt }

// GetDescription returns Release.Description, and is useful for accessing the field via an interface.
func (v *Release) GetDescription() string { return v.Description }

// GetUrl returns Release.Url, and is useful for accessing the field via an interface.
func (v *Release) GetUrl() string { return v.Url }

// RemoveLabelResult includes the requested fields of the GraphQL type RemoveLabelsFromLabelablePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of RemoveLabelsFromLabelable.
type RemoveLabelResult struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
}

// GetClientMutationId returns RemoveLabelResult.ClientMutationId, and is useful for accessing the field via an interface.
func (v *RemoveLabelResult) GetClientMutationId() string { return v.ClientMutationId }

// RemoveLabelsResponse is returned by RemoveLabels on success.
type RemoveLabelsResponse struct {
	// Removes labels from a Labelable object.
	RemoveLabelsFromLabelable RemoveLabelResult `json:"removeLabelsFromLabelable"`
}

// GetRemoveLabelsFromLabelable returns RemoveLabelsResponse.RemoveLabelsFromLabelable, and is useful for accessing the field via an interface.
func (v *RemoveLabelsResponse) GetRemoveLabelsFromLabelable() RemoveLabelResult {
	return v.RemoveLabelsFromLabelable
}

// RepoLabels includes the requested fields of the GraphQL type LabelConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Label.
type RepoLabels struct {
	// A list of nodes.
	Nodes []RepoLabelsNodesLabel `json:"nodes"`
}

// GetNodes returns RepoLabels.Nodes, and is useful for accessing the field via an interface.
func (v *RepoLabels) GetNodes() []RepoLabelsNodesLabel { return v.Nodes }

// RepoLabelsNodesLabel includes the requested fields of the GraphQL type Label.
// The GraphQL type's documentation follows.
//
// A label for categorizing Issues, Pull Requests, Milestones, or Discussions with a given Repository.
type RepoLabelsNodesLabel struct {
	Label `json:"-"`
	// A list of pull requests associated with this label.
	PullRequests RepoLabelsNodesLabelPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns RepoLabelsNodesLabel.PullRequests, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabel) GetPullRequests() RepoLabelsNodesLabelPullRequestsPullRequestConnection {
	return v.PullRequests
}

// GetName returns RepoLabelsNodesLabel.Name, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabel) GetName() string { return v.Label.Name }

// GetId returns RepoLabelsNodesLabel.Id, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabel) GetId() string { return v.Label.Id }

// GetColor returns RepoLabelsNodesLabel.Color, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabel) GetColor() string { return v.Label.Color }

// GetDescription returns RepoLabelsNodesLabel.Description, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabel) GetDescription() string { return v.Label.Description }

func (v *RepoLabelsNodesLabel) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*RepoLabelsNodesLabel
		graphql.NoUnmarshalJSON
	}
	firstPass.RepoLabelsNodesLabel = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Label)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalRepoLabelsNodesLabel struct {
	PullRequests RepoLabelsNodesLabelPullRequestsPullRequestConnection `json:"pullRequests"`

	Name string `json:"name"`

	Id string `json:"id"`

	Color string `json:"color"`

	Description string `json:"description"`
}

func (v *RepoLabelsNodesLabel) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *RepoLabelsNodesLabel) __premarshalJSON() (*__premarshalRepoLabelsNodesLabel, error) {
	var retval __premarshalRepoLabelsNodesLabel

	retval.PullRequests = v.PullRequests
	retval.Name = v.Label.Name
	retval.Id = v.Label.Id
	retval.Color = v.Label.Color
	retval.Description = v.Label.Description
	return &retval, nil
}

// RepoLabelsNodesLabelPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
// The GraphQL type's documentation follows.
//
// The connection type for PullRequest.
type RepoLabelsNodesLabelPullRequestsPullRequestConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetTotalCount returns RepoLabelsNodesLabelPullRequestsPullRequestConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *RepoLabelsNodesLabelPullRequestsPullRequestConnection) GetTotalCount() int {
	return v.TotalCount
}

// __AddLabelsInput is used internally by genqlient
type __AddLabelsInput struct {
	PrID     string   `json:"prID"`
	LabelIDs []string `json:"labelIDs"`
}

// GetPrID returns __AddLabelsInput.PrID, and is useful for accessing the field via an interface.
func (v *__AddLabelsInput) GetPrID() string { return v.PrID }

// GetLabelIDs returns __AddLabelsInput.LabelIDs, and is useful for accessing the field via an interface.
func (v *__AddLabelsInput) GetLabelIDs() []string { return v.LabelIDs }

// __ClosePullRequestInput is used internally by genqlient
type __ClosePullRequestInput struct {
	PrID string `json:"prID"`
}

// GetPrID returns __ClosePullRequestInput.PrID, and is useful for accessing the field via an interface.
func (v *__ClosePullRequestInput) GetPrID() string { return v.PrID }

// __CreateLabelInput is used internally by genqlient
type __CreateLabelInput struct {
	RepoID      string `json:"repoID"`
	Color       string `json:"color"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// GetRepoID returns __CreateLabelInput.RepoID, and is useful for accessing the field via an interface.
func (v *__CreateLabelInput) GetRepoID() string { return v.RepoID }

// GetColor returns __CreateLabelInput.Color, and is useful for accessing the field via an interface.
func (v *__CreateLabelInput) GetColor() string { return v.Color }

// GetName returns __CreateLabelInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateLabelInput) GetName() string { return v.Name }

// GetDescription returns __CreateLabelInput.Description, and is useful for accessing the field via an interface.
func (v *__CreateLabelInput) GetDescription() string { return v.Description }

// __CreatePullRequestInput is used internally by genqlient
type __CreatePullRequestInput struct {
	BaseRefName  string `json:"baseRefName"`
	Body         string `json:"body"`
	HeadRefName  string `json:"headRefName"`
	RepositoryId string `json:"repositoryId"`
	Title        string `json:"title"`
}

// GetBaseRefName returns __CreatePullRequestInput.BaseRefName, and is useful for accessing the field via an interface.
func (v *__CreatePullRequestInput) GetBaseRefName() string { return v.BaseRefName }

// GetBody returns __CreatePullRequestInput.Body, and is useful for accessing the field via an interface.
func (v *__CreatePullRequestInput) GetBody() string { return v.Body }

// GetHeadRefName returns __CreatePullRequestInput.HeadRefName, and is useful for accessing the field via an interface.
func (v *__CreatePullRequestInput) GetHeadRefName() string { return v.HeadRefName }

// GetRepositoryId returns __CreatePullRequestInput.RepositoryId, and is useful for accessing the field via an interface.
func (v *__CreatePullRequestInput) GetRepositoryId() string { return v.RepositoryId }

// GetTitle returns __CreatePullRequestInput.Title, and is useful for accessing the field via an interface.
func (v *__CreatePullRequestInput) GetTitle() string { return v.Title }

// __CreateRefInput is used internally by genqlient
type __CreateRefInput struct {
	RepoID string `json:"repoID"`
	Oid    string `json:"oid"`
	Name   string `json:"name"`
}

// GetRepoID returns __CreateRefInput.RepoID, and is useful for accessing the field via an interface.
func (v *__CreateRefInput) GetRepoID() string { return v.RepoID }

// GetOid returns __CreateRefInput.Oid, and is useful for accessing the field via an interface.
func (v *__CreateRefInput) GetOid() string { return v.Oid }

// GetName returns __CreateRefInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateRefInput) GetName() string { return v.Name }

// __DeleteLabelInput is used internally by genqlient
type __DeleteLabelInput struct {
	Id string `json:"id"`
}

// GetId returns __DeleteLabelInput.Id, and is useful for accessing the field via an interface.
func (v *__DeleteLabelInput) GetId() string { return v.Id }

// __GetPullRequestInput is used internally by genqlient
type __GetPullRequestInput struct {
	Owner  string `json:"owner"`
	Repo   string `json:"repo"`
	Number int    `json:"number"`
}

// GetOwner returns __GetPullRequestInput.Owner, and is useful for accessing the field via an interface.
func (v *__GetPullRequestInput) GetOwner() string { return v.Owner }

// GetRepo returns __GetPullRequestInput.Repo, and is useful for accessing the field via an interface.
func (v *__GetPullRequestInput) GetRepo() string { return v.Repo }

// GetNumber returns __GetPullRequestInput.Number, and is useful for accessing the field via an interface.
func (v *__GetPullRequestInput) GetNumber() int { return v.Number }

// __GetRepoInput is used internally by genqlient
type __GetRepoInput struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

// GetOwner returns __GetRepoInput.Owner, and is useful for accessing the field via an interface.
func (v *__GetRepoInput) GetOwner() string { return v.Owner }

// GetRepo returns __GetRepoInput.Repo, and is useful for accessing the field via an interface.
func (v *__GetRepoInput) GetRepo() string { return v.Repo }

// __RemoveLabelsInput is used internally by genqlient
type __RemoveLabelsInput struct {
	PrID     string   `json:"prID"`
	LabelIDs []string `json:"labelIDs"`
}

// GetPrID returns __RemoveLabelsInput.PrID, and is useful for accessing the field via an interface.
func (v *__RemoveLabelsInput) GetPrID() string { return v.PrID }

// GetLabelIDs returns __RemoveLabelsInput.LabelIDs, and is useful for accessing the field via an interface.
func (v *__RemoveLabelsInput) GetLabelIDs() []string { return v.LabelIDs }

// __getPullRequestsInput is used internally by genqlient
type __getPullRequestsInput struct {
	Owner       string   `json:"owner"`
	Repo        string   `json:"repo"`
	BaseRefName string   `json:"baseRefName"`
	Labels      []string `json:"labels"`
	PrAfter     string   `json:"prAfter"`
}

// GetOwner returns __getPullRequestsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetOwner() string { return v.Owner }

// GetRepo returns __getPullRequestsInput.Repo, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetRepo() string { return v.Repo }

// GetBaseRefName returns __getPullRequestsInput.BaseRefName, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetBaseRefName() string { return v.BaseRefName }

// GetLabels returns __getPullRequestsInput.Labels, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetLabels() []string { return v.Labels }

// GetPrAfter returns __getPullRequestsInput.PrAfter, and is useful for accessing the field via an interface.
func (v *__getPullRequestsInput) GetPrAfter() string { return v.PrAfter }

// __getReleasesInput is used internally by genqlient
type __getReleasesInput struct {
	Owner    string `json:"owner"`
	Repo     string `json:"repo"`
	PageSize int    `json:"pageSize"`
	After    string `json:"after"`
}

// GetOwner returns __getReleasesInput.Owner, and is useful for accessing the field via an interface.
func (v *__getReleasesInput) GetOwner() string { return v.Owner }

// GetRepo returns __getReleasesInput.Repo, and is useful for accessing the field via an interface.
func (v *__getReleasesInput) GetRepo() string { return v.Repo }

// GetPageSize returns __getReleasesInput.PageSize, and is useful for accessing the field via an interface.
func (v *__getReleasesInput) GetPageSize() int { return v.PageSize }

// GetAfter returns __getReleasesInput.After, and is useful for accessing the field via an interface.
func (v *__getReleasesInput) GetAfter() string { return v.After }

// __getTagsInput is used internally by genqlient
type __getTagsInput struct {
	Owner    string `json:"owner"`
	Repo     string `json:"repo"`
	PageSize int    `json:"pageSize"`
	After    string `json:"after"`
}

// GetOwner returns __getTagsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getTagsInput) GetOwner() string { return v.Owner }

// GetRepo returns __getTagsInput.Repo, and is useful for accessing the field via an interface.
func (v *__getTagsInput) GetRepo() string { return v.Repo }

// GetPageSize returns __getTagsInput.PageSize, and is useful for accessing the field via an interface.
func (v *__getTagsInput) GetPageSize() int { return v.PageSize }

// GetAfter returns __getTagsInput.After, and is useful for accessing the field via an interface.
func (v *__getTagsInput) GetAfter() string { return v.After }

// getPullRequestsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestsRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests PullRequestsResult `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestsRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestsRepository) GetPullRequests() PullRequestsResult { return v.PullRequests }

// getPullRequestsResponse is returned by getPullRequests on success.
type getPullRequestsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestsRepository `json:"repository"`
}

// GetRepository returns getPullRequestsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestsResponse) GetRepository() getPullRequestsRepository { return v.Repository }

// getReleasesRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getReleasesRepository struct {
	// List of releases which are dependent on this repository.
	Releases getReleasesRepositoryReleasesReleaseConnection `json:"releases"`
}

// GetReleases returns getReleasesRepository.Releases, and is useful for accessing the field via an interface.
func (v *getReleasesRepository) GetReleases() getReleasesRepositoryReleasesReleaseConnection {
	return v.Releases
}

// getReleasesRepositoryReleasesReleaseConnection includes the requested fields of the GraphQL type ReleaseConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Release.
type getReleasesRepositoryReleasesReleaseConnection struct {
	// Information to aid in pagination.
	PageInfo PageInfo `json:"pageInfo"`
	// A list of nodes.
	Nodes []Release `json:"nodes"`
}

// GetPageInfo returns getReleasesRepositoryReleasesReleaseConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getReleasesRepositoryReleasesReleaseConnection) GetPageInfo() PageInfo { return v.PageInfo }

// GetNodes returns getReleasesRepositoryReleasesReleaseConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getReleasesRepositoryReleasesReleaseConnection) GetNodes() []Release { return v.Nodes }

// getReleasesResponse is returned by getReleases on success.
type getReleasesResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getReleasesRepository `json:"repository"`
}

// GetRepository returns getReleasesResponse.Repository, and is useful for accessing the field via an interface.
func (v *getReleasesResponse) GetRepository() getReleasesRepository { return v.Repository }

// getTagsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getTagsRepository struct {
	// Fetch a list of refs from the repository
	Refs getTagsRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getTagsRepository.Refs, and is useful for accessing the field via an interface.
func (v *getTagsRepository) GetRefs() getTagsRepositoryRefsRefConnection { return v.Refs }

// getTagsRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Ref.
type getTagsRepositoryRefsRefConnection struct {
	// Information to aid in pagination.
	PageInfo PageInfo `json:"pageInfo"`
	// A list of nodes.
	Nodes []Ref `json:"nodes"`
}

// GetPageInfo returns getTagsRepositoryRefsRefConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *getTagsRepositoryRefsRefConnection) GetPageInfo() PageInfo { return v.PageInfo }

// GetNodes returns getTagsRepositoryRefsRefConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getTagsRepositoryRefsRefConnection) GetNodes() []Ref { return v.Nodes }

// getTagsResponse is returned by getTags on success.
type getTagsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getTagsRepository `json:"repository"`
}

// GetRepository returns getTagsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getTagsResponse) GetRepository() getTagsRepository { return v.Repository }

// The mutation executed by AddLabels.
const AddLabels_Operation = `
mutation AddLabels ($prID: ID!, $labelIDs: [ID!]!) {
	addLabelsToLabelable(input: {labelableId:$prID,labelIds:$labelIDs}) {
		clientMutationId
	}
}
`

func AddLabels(
	ctx_ context.Context,
	client_ graphql.Client,
	prID string,
	labelIDs []string,
) (data_ *AddLabelsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AddLabels",
		Query:  AddLabels_Operation,
		Variables: &__AddLabelsInput{
			PrID:     prID,
			LabelIDs: labelIDs,
		},
	}

	data_ = &AddLabelsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ClosePullRequest.
const ClosePullRequest_Operation = `
mutation ClosePullRequest ($prID: ID!) {
	closePullRequest(input: {pullRequestId:$prID}) {
		clientMutationId
	}
}
`

func ClosePullRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	prID string,
) (data_ *ClosePullRequestResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ClosePullRequest",
		Query:  ClosePullRequest_Operation,
		Variables: &__ClosePullRequestInput{
			PrID: prID,
		},
	}

	data_ = &ClosePullRequestResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateLabel.
const CreateLabel_Operation = `
mutation CreateLabel ($repoID: ID!, $color: String!, $name: String!, $description: String) {
	createLabel(input: {repositoryId:$repoID,color:$color,name:$name,description:$description}) {
		label {
			id
		}
	}
}
`

func CreateLabel(
	ctx_ context.Context,
	client_ graphql.Client,
	repoID string,
	color string,
	name string,
	description string,
) (data_ *CreateLabelResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateLabel",
		Query:  CreateLabel_Operation,
		Variables: &__CreateLabelInput{
			RepoID:      repoID,
			Color:       color,
			Name:        name,
			Description: description,
		},
	}

	data_ = &CreateLabelResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreatePullRequest.
const CreatePullRequest_Operation = `
mutation CreatePullRequest ($baseRefName: String!, $body: String, $headRefName: String!, $repositoryId: ID!, $title: String!) {
	createPullRequest(input: {repositoryId:$repositoryId,baseRefName:$baseRefName,headRefName:$headRefName,title:$title,body:$body}) {
		... CreatePullRequestFields
	}
}
fragment CreatePullRequestFields on CreatePullRequestPayload {
	pullRequest {
		... PullRequest
	}
}
fragment PullRequest on PullRequest {
	title
	id
	resourcePath
	permalink
	url
	createdAt
	closed
	merged
	number
	author {
		__typename
		login
	}
	labels(first: 100, orderBy: {field:NAME,direction:ASC}) {
		nodes {
			... Label
		}
		pageInfo {
			... PageInfo
		}
	}
}
fragment Label on Label {
	name
	id
	color
	description
}
fragment PageInfo on PageInfo {
	endCursor
	hasNextPage
}
`

func CreatePullRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	baseRefName string,
	body string,
	headRefName string,
	repositoryId string,
	title string,
) (data_ *CreatePullRequestResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreatePullRequest",
		Query:  CreatePullRequest_Operation,
		Variables: &__CreatePullRequestInput{
			BaseRefName:  baseRefName,
			Body:         body,
			HeadRefName:  headRefName,
			RepositoryId: repositoryId,
			Title:        title,
		},
	}

	data_ = &CreatePullRequestResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateRef.
const CreateRef_Operation = `
mutation CreateRef ($repoID: ID!, $oid: GitObjectID!, $name: String!) {
	createRef(input: {repositoryId:$repoID,oid:$oid,name:$name}) {
		ref {
			id
			name
			target {
				__typename
				id
				commitResourcePath
				oid
			}
		}
	}
}
`

func CreateRef(
	ctx_ context.Context,
	client_ graphql.Client,
	repoID string,
	oid string,
	name string,
) (data_ *CreateRefResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateRef",
		Query:  CreateRef_Operation,
		Variables: &__CreateRefInput{
			RepoID: repoID,
			Oid:    oid,
			Name:   name,
		},
	}

	data_ = &CreateRefResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by DeleteLabel.
const DeleteLabel_Operation = `
mutation DeleteLabel ($id: ID!) {
	deleteLabel(input: {id:$id}) {
		clientMutationId
	}
}
`

func DeleteLabel(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *DeleteLabelResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeleteLabel",
		Query:  DeleteLabel_Operation,
		Variables: &__DeleteLabelInput{
			Id: id,
		},
	}

	data_ = &DeleteLabelResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetPullRequest.
const GetPullRequest_Operation = `
query GetPullRequest ($owner: String!, $repo: String!, $number: Int!) {
	repository(owner: $owner, name: $repo) {
		pullRequest(number: $number) {
			... PullRequest
			labels(first: 100, orderBy: {field:NAME,direction:ASC}) {
				nodes {
					... Label
				}
			}
		}
	}
}
fragment PullRequest on PullRequest {
	title
	id
	resourcePath
	permalink
	url
	createdAt
	closed
	merged
	number
	author {
		__typename
		login
	}
	labels(first: 100, orderBy: {field:NAME,direction:ASC}) {
		nodes {
			... Label
		}
		pageInfo {
			... PageInfo
		}
	}
}
fragment Label on Label {
	name
	id
	color
	description
}
fragment PageInfo on PageInfo {
	endCursor
	hasNextPage
}
`

func GetPullRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	number int,
) (data_ *GetPullRequestResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPullRequest",
		Query:  GetPullRequest_Operation,
		Variables: &__GetPullRequestInput{
			Owner:  owner,
			Repo:   repo,
			Number: number,
		},
	}

	data_ = &GetPullRequestResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetRepo.
const GetRepo_Operation = `
query GetRepo ($owner: String!, $repo: String!) {
	repository(owner: $owner, name: $repo) {
		id
		labels(first: 100, orderBy: {field:NAME,direction:ASC}) {
			nodes {
				... Label
				pullRequests(first: 1) {
					totalCount
				}
			}
		}
	}
}
fragment Label on Label {
	name
	id
	color
	description
}
`

func GetRepo(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
) (data_ *GetRepoResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetRepo",
		Query:  GetRepo_Operation,
		Variables: &__GetRepoInput{
			Owner: owner,
			Repo:  repo,
		},
	}

	data_ = &GetRepoResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RemoveLabels.
const RemoveLabels_Operation = `
mutation RemoveLabels ($prID: ID!, $labelIDs: [ID!]!) {
	removeLabelsFromLabelable(input: {labelableId:$prID,labelIds:$labelIDs}) {
		clientMutationId
	}
}
`

func RemoveLabels(
	ctx_ context.Context,
	client_ graphql.Client,
	prID string,
	labelIDs []string,
) (data_ *RemoveLabelsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RemoveLabels",
		Query:  RemoveLabels_Operation,
		Variables: &__RemoveLabelsInput{
			PrID:     prID,
			LabelIDs: labelIDs,
		},
	}

	data_ = &RemoveLabelsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getPullRequests.
const getPullRequests_Operation = `
query getPullRequests ($owner: String!, $repo: String!, $baseRefName: String!, $labels: [String!], $prAfter: String) {
	repository(owner: $owner, name: $repo) {
		pullRequests(states: [MERGED,OPEN], baseRefName: $baseRefName, labels: $labels, first: 20, after: $prAfter) {
			nodes {
				... PullRequest
			}
			pageInfo {
				... PageInfo
			}
		}
	}
}
fragment PullRequest on PullRequest {
	title
	id
	resourcePath
	permalink
	url
	createdAt
	closed
	merged
	number
	author {
		__typename
		login
	}
	labels(first: 100, orderBy: {field:NAME,direction:ASC}) {
		nodes {
			... Label
		}
		pageInfo {
			... PageInfo
		}
	}
}
fragment PageInfo on PageInfo {
	endCursor
	hasNextPage
}
fragment Label on Label {
	name
	id
	color
	description
}
`

func getPullRequests(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	baseRefName string,
	labels []string,
	prAfter string,
) (data_ *getPullRequestsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getPullRequests",
		Query:  getPullRequests_Operation,
		Variables: &__getPullRequestsInput{
			Owner:       owner,
			Repo:        repo,
			BaseRefName: baseRefName,
			Labels:      labels,
			PrAfter:     prAfter,
		},
	}

	data_ = &getPullRequestsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getReleases.
const getReleases_Operation = `
query getReleases ($owner: String!, $repo: String!, $pageSize: Int!, $after: String) {
	repository(owner: $owner, name: $repo) {
		releases(first: $pageSize, after: $after, orderBy: {direction:DESC,field:NAME}) {
			pageInfo {
				... PageInfo
			}
			nodes {
				... Release
			}
		}
	}
}
fragment PageInfo on PageInfo {
	endCursor
	hasNextPage
}
fragment Release on Release {
	id
	name
	tagName
	createdAt
	publishedAt
	description
	url
}
`

func getReleases(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	pageSize int,
	after string,
) (data_ *getReleasesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getReleases",
		Query:  getReleases_Operation,
		Variables: &__getReleasesInput{
			Owner:    owner,
			Repo:     repo,
			PageSize: pageSize,
			After:    after,
		},
	}

	data_ = &getReleasesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getTags.
const getTags_Operation = `
query getTags ($owner: String!, $repo: String!, $pageSize: Int!, $after: String) {
	repository(owner: $owner, name: $repo) {
		refs(first: $pageSize, after: $after, refPrefix: "refs/tags/", orderBy: {direction:DESC,field:TAG_COMMIT_DATE}) {
			pageInfo {
				... PageInfo
			}
			nodes {
				... Ref
			}
		}
	}
}
fragment PageInfo on PageInfo {
	endCursor
	hasNextPage
}
fragment Ref on Ref {
	id
	name
	target {
		__typename
		oid
	}
}
`

func getTags(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	pageSize int,
	after string,
) (data_ *getTagsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getTags",
		Query:  getTags_Operation,
		Variables: &__getTagsInput{
			Owner:    owner,
			Repo:     repo,
			PageSize: pageSize,
			After:    after,
		},
	}

	data_ = &getTagsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
